[options]
  colorscheme = "one"
  colorscheme_bg = "dark"
  enable_guicolors = true

  statusline_separator = "arrow"
  statusline_inactive_separator = "arrow"
  buffer_index_type = 3
  statusline_unicode_symbols = false
  enable_tabline_filetype_icon = false
  enable_statusline_mode = false
  
  filemanager = "vimfiler"

[[layers]]
  name = 'core'
  filetree_show_hidden = true

[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "smart"

[[layers]]
  name = 'colorscheme'

[[layers]]
  name = 'ctrlp'

[[layers]]
  name = 'shell'
  default_position = "top"
  default_height = 30

[[layers]]
  name = 'sudo'

[[layers]]
  name = 'tmux'

